print("Hello, World!")
print("Zhibek")
print("Oomat")
print("Ali")
print("Renat")
print("Iskender")
print("Manas")
print("Zhayil")
print("Daulet")
print("Kanyshai")
print("Beknazar")
print("Eliza")
print("Assat")
print("Altynai")